- name: Deploy WAR to local Tomcat
  hosts: localhost
  become: yes
  connection: local

  vars:
    tomcat_dir: /home/ubuntu/pradyumn/apache-tomcat-9.0.107
    war_dest: "{{ tomcat_dir }}/webapps/poc-2.war"

  tasks:
    - name: Stop Tomcat
      shell: "{{ tomcat_dir }}/bin/shutdown.sh || true"

    - name: Remove existing exploded WAR folder
      file:
        path: "{{ war_dest | regex_replace('\\.war$', '') }}"
        state: absent

    - name: Copy WAR to Tomcat webapps
      copy:
        src: "{{ war_src }}"
        dest: "{{ war_dest }}"
        mode: '0644'

    - name: Start Tomcat
      shell: "{{ tomcat_dir }}/bin/startup.sh"
